---
lang: fr
format:
  pdf:
    toc: false
    lof: false
    lot: false
    toc-depth: 3
    number-sections: true
    include-in-header: header.tex
    linkcolor: black
---


\maketitle
\thispagestyle{empty}
\newpage

\setcounter{page}{1}

\renewcommand{\contentsname}{Sommaire}

\tableofcontents


\newpage
# Introduction {.unnumbered}

\newpage
# Présentation du projet


## Contexte


## Besoins fonctionnels

\newpage 
## Présentation des données 

Nous avons choisi d’utiliser seulement certains jeux de données parmi ceux proposés afin de modéliser notre application. Notre sélection a été pensée pour diversifier au maximum notre approche : nous avons ainsi veillé à inclure à la fois un sport collectif et un sport individuel, tout en intégrant des données issues du sport féminin. Dans cette optique, nous avons travaillé à partir des fichiers suivants :

* **Basket-ball** :
    * `game.csv` : Données sur les matchs NBA.
    * `player.csv` : Informations sur les joueurs NBA.
    * `team.csv` : Informations sur les équipes NBA.

* **Tennis** :
    * `atp_matches_2024.csv` : Résultats détaillés des matchs du circuit ATP.
    * `atp_players_2024.csv` : Informations sur les joueurs du circuit ATP.
    * `wta_matches_2024.csv` : Résultats détaillés des matchs du circuit WTA.
    * `wta_players_2024.csv` : Informations sur les joueuses du circuit WTA.


Avant de débuter l’analyse de nos différents jeux de données sportives, nous avons réalisé une phase d’exploration approfondie afin d'en garantir la fiabilité. Cette étape a consisté à identifier d'éventuels doublons et à recenser les valeurs manquantes qui auraient pu provoquer des erreurs lors de certaines demandes. Ces vérifications préliminaires nous permettent de confirmer que les bases de données sont exploitables.

\newpage 
# Conception de l’application

## Modélisation

- diagramme de classe
- diagramme de cas d'utilisation
- (diagramme d'activité)

## Architecture générale 

Notre projet repose sur une structure orientée objet qui privilégie la modularité et l'organisation. L’architecture repose sur plusieurs modules, chacun ayant
une responsabilité bien définie :

(faire l'architecture du code : cf page 4 rapport Lina)

## Choix technologiques

\newpage
# Réalisation

## Organisation du travail

L’organisation de ce projet a débuté par une phase de réflexion collective afin de structurer les axes majeurs de développement de l'application. Cette première étape de modélisation nous a permis d'accorder nos visions techniques avant que l'arrivée concrète des jeux de données ne nous permette d'affiner la structure des classes et la logique des méthodes de traitement. 

Une fois ce cadre méthodologique établi, nous avons réparti le développement technique de la façon suivante : Théau s’est occupé de la gestion du flux de données, développant les scripts d’insertion et les adaptateurs nécessaires à l’intégration, tandis que Milyan s’est concentré sur l’architecture logicielle en codant l’ensemble des classes structurantes du système. En parallèle, Gwenaël a pris en charge le contrôle qualité à travers la vérification de la propreté des données, tout en concevant l’interface utilisateur afin de permettre une accessibilité simple aux données. 

(faire le paragraphe sur les tests)

Afin de fluidifier notre collaboration et d'assurer la cohérence de notre développement, nous avons utilisé Git. Cet outil a été indispensable pour travailler simultanément sur le même code source, gérer les fusions de nos travaux respectifs et conserver un historique rigoureux de chaque étape du projet. 

Nous avons ensuite rédigé le rapport tous les trois, en choisissant d'utiliser l'outil Quarto.


## Développement

## Difficultés rencontrées

L’une des principales difficultés de ce projet a résidé dans son démarrage : en l'absence de sujet imposé et n'ayant pas encore les jeux de données à notre disposition, il a été particulièrement complexe de lancer une dynamique de travail concrète. Cette phase d'incertitude a rendu difficile la définition du concept même de notre future application, car il est délicat de structurer une architecture logicielle ou d'imaginer des fonctionnalités pertinentes sans connaître la nature exacte, le volume et les contraintes des données à traiter. 


(faire difficultés sur le code)

\newpage
# Tests et validation

## Stratégie de test

Pour garantir la fiabilité de notre application, nous avons mis en place une stratégie de tests unitaires et d'intégration basée sur le framework Pytest. L'objectif est double : assurer l'exactitude des calculs statistiques et garantir la robustesse des processus d'importation.

La validation commence avec les modèles et les adaptateurs. Les tests sur les modèles garantissent que chaque objet métier, comme un match ou un joueur, est instancié avec des données saines et que ses propriétés calculées (par exemple, la concaténation du nom complet) se comportent de manière prévisible. Parallèlement, la couche des adaptateurs fait l'objet d'une attention critique. Nous y testons le mapping entre le format brut des dictionnaires issus du CSV et nos objets Python, en mettant à l'épreuve la gestion des valeurs manquantes et la précision des conversions techniques, telles que la transformation des poids de lbs en kg.

Le cœur du programme, regroupé dans la partie services, est quant à lui vérifié par des tests précis sur les calculs et les règles de gestion. Ces tests permettent de contrôler que les classements des équipes, les moyennes de points ou encore l'historique des joueurs sont calculés sans aucune erreur. Pour que ces vérifications soient fiables et rapides, nous utilisons des simulations (appelées "Mocks") qui remplacent les fichiers réels par des données fictives mais contrôlées. Cela nous permet de tester le "cerveau" de l'application de façon isolée, en étant certains que si un résultat est faux, cela vient d'une erreur de calcul et non d'un problème technique lié au chargement des données.

Enfin, la fiabilité de la persistance et de l'accès aux données est assurée par des tests aux frontières au niveau des repositories et des importeurs. Nous utilisons des environnements de fichiers temporaires via *tmp_path*. Cette méthode nous permet de vérifier, dans des conditions quasi réelles, que le système gère correctement les différents séparateurs et l'encodage des fichiers CSV. Cette stratégie globale assure ainsi une interface fluide et sécurisée entre le stockage physique et la logique métier de l'application.

## Quelques résultats

## Limites de l’application

Le choix de nous concentrer exclusivement sur deux sports rend l'application particulièrement spécifique. L'interface utilisateur ayant été finement adaptée aux caractéristiques propres de ces disciplines, cette spécialisation crée une contrainte majeure en termes d'évolutivité : l'ajout d'un nouveau sport s'avère complexe. En effet, chaque nouvelle catégorie nécessiterait une adaptation de l'interface pour répondre à ses spécificités, ce qui limite sa capacité à s'ouvrir à d'autres domaines sportifs sans un travail de développement supplémentaire conséquent.



\newpage 
# Conclusion {.unnumbered}

\newpage 

# Annexes {.unnumbered}


```{r}

```

